<?php

namespace Tests\AppBundle\Hashtest;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-06 at 13:35:52.
 */
class HashApiClientTest extends WebTestCase {

    public function testGetHash() {
        
        $client = static::createClient();
        $container = $client->getContainer();

        $hash = $container->get('hashapi')->getHash([
            'firstname'=>'a', 
            'lastname'=>'a'
        ]);
        $this->assertEquals('2a4426e73d4051ce4d2422a1c15a4fdb69275596', $hash);
    }

}
