<?php

namespace Tests\AppBundle\Hashtest;

use AppBundle\Hashtest\HashApiClient;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-06 at 13:35:52.
 */
class HashApiClientTest extends \PHPUnit_Framework_TestCase {

    public function testGetHash() {
        // Remove the following lines when you implement this test.
        $hash = HashApiClient::getHash(
            [
                'firstname' => 'a',
                'lastname' => 'a',
            ]
        );
        $this->assertEquals('2a4426e73d4051ce4d2422a1c15a4fdb69275596', $hash);
    }

}
