<?php

namespace AppBundle\Repository;

/**
 * HashTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HashTestRepository extends \Doctrine\ORM\EntityRepository
{
}
