@startuml

class hashApiClient{
    __construct(api_username, api_password)
    getHash(data[]) : String
}

class hashApiFactory{
    {static} getHashApi(data[], api_config[]) : hashApiInterface
}

interface hashApiInterface{
    create($data[], api_config[])
    getHash() : String
}

class hashApi1 implements hashApiInterface{
    create($data[], api_config[])
    getHash() : String
}

hashApiFactory->hashApiInterface
hashApiClient->hashApiFactory

@enduml
