@startuml

class hashApiClient{
    {static} getHash(data[] : String) : String
}

class hashApiFactory{
    getHashApi(data[] : String, hashApiVersion : int) : hashApiInterface
}

interface hashApiInterface{
    create($data[] : String)
    getHash() : String
}

class hashApi1 implements hashApiInterface{
    create($data[] : String)
    getHash() : String
}

hashApiFactory->hashApiInterface
hashApiClient->hashApiFactory

@enduml
